### ISSUE TITLE
Build Broken

### ISSUE THREAD

**Issue by appinteractive** [operando/advertising_id#20]
After updating to 2.1.0 the `flutter build appbundle` crashes with following logs (only for android):

```
[        ] > Task :advertising_id:compileReleaseAidl NO-SOURCE
[        ] > Task :advertising_id:compileReleaseRenderscript NO-SOURCE
[        ] > Task :advertising_id:generateReleaseBuildConfig UP-TO-DATE
[        ] > Task :advertising_id:generateReleaseResValues UP-TO-DATE
[        ] > Task :advertising_id:generateReleaseResources UP-TO-DATE
[        ] > Task :advertising_id:packageReleaseResources UP-TO-DATE
[        ] > Task :advertising_id:parseReleaseLocalResources UP-TO-DATE
[        ] > Task :advertising_id:processReleaseManifest UP-TO-DATE
[  +92 ms] > Task :advertising_id:generateReleaseRFile UP-TO-DATE
[ +604 ms] > Task :advertising_id:compileReleaseKotlin FAILED
[        ] e: Incompatible classes were found in dependencies. Remove them from the classpath or use
'-Xskip-metadata-version-check' to suppress errors
[   +2 ms] e:
/Users/USERNAME/.gradle/caches/transforms-3/38a7fea0325bf765d81c8dc3c120c305/transformed/jetified-kotlin-
stdlib-jdk7-1.5.31.jar!/META-INF/kotlin-stdlib-jdk7.kotlin_module: Module was compiled with an
incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is
1.1.15.
[        ] e:
/Users/USERNAME/.gradle/caches/transforms-3/6c87f3acbf13b40ac5e88ec17ade8676/transformed/jetified-kotlin-
stdlib-1.5.31.jar!/META-INF/kotlin-stdlib.kotlin_module: Module was compiled with an incompatible
version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
[        ] e:
/Users/USERNAME/.gradle/caches/transforms-3/fb601dcdc6c034b07b15c8ea122906d5/transformed/jetified-kotlin-
stdlib-common-1.5.31.jar!/META-INF/kotlin-stdlib-common.kotlin_module: Module was compiled with an
incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is
1.1.15.
[        ] e:
/Users/USERNAME/.pub-cache/hosted/pub.dartlang.org/advertising_id-2.1.0/android/src/main/kotlin/com/os/op
erando/advertisingid/AdvertisingIdPlugin.kt: (14, 26): Unresolved reference: thread
[        ] e:
/Users/USERNAME/.pub-cache/hosted/pub.dartlang.org/advertising_id-2.1.0/android/src/main/kotlin/com/os/op
erando/advertisingid/AdvertisingIdPlugin.kt: (20, 10): Class 'kotlin.jvm.JvmStatic' was compiled with
an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is
1.1.15.
[        ] The class is loaded from
/Users/USERNAME/.gradle/caches/transforms-3/6c87f3acbf13b40ac5e88ec17ade8676/transformed/jetified-kotlin-
stdlib-1.5.31.jar!/kotlin/jvm/JvmStatic.class
[        ] e:
/Users/USERNAME/.pub-cache/hosted/pub.dartlang.org/advertising_id-2.1.0/android/src/main/kotlin/com/os/op
erando/advertisingid/AdvertisingIdPlugin.kt: (24, 20): Class 'kotlin.Unit' was compiled with an
incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is
1.1.15.
[        ] The class is loaded from
/Users/USERNAME/.gradle/caches/transforms-3/6c87f3acbf13b40ac5e88ec17ade8676/transformed/jetified-kotlin-
stdlib-1.5.31.jar!/kotlin/Unit.class
[        ] e:
/Users/USERNAME/.pub-cache/hosted/pub.dartlang.org/advertising_id-2.1.0/android/src/main/kotlin/com/os/op
erando/advertisingid/AdvertisingIdPlugin.kt: (25, 21): Class 'kotlin.Unit' was compiled with an
incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is
1.1.15.
[        ] The class is loaded from
/Users/USERNAME/.gradle/caches/transforms-3/6c87f3acbf13b40ac5e88ec17ade8676/transformed/jetified-kotlin-
stdlib-1.5.31.jar!/kotlin/Unit.class
[        ] e:
/Users/USERNAME/.pub-cache/hosted/pub.dartlang.org/advertising_id-2.1.0/android/src/main/kotlin/com/os/op
erando/advertisingid/AdvertisingIdPlugin.kt: (31, 17): Class 'kotlin.Unit' was compiled with an
incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is
1.1.15.
[        ] The class is loaded from
/Users/USERNAME/.gradle/caches/transforms-3/6c87f3acbf13b40ac5e88ec17ade8676/transformed/jetified-kotlin-
stdlib-1.5.31.jar!/kotlin/Unit.class
[        ] e:
/Users/USERNAME/.pub-cache/hosted/pub.dartlang.org/advertising_id-2.1.0/android/src/main/kotlin/com/os/op
erando/advertisingid/AdvertisingIdPlugin.kt: (38, 9): Class 'kotlin.Unit' was compiled with an
incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is
1.1.15.
[        ] The class is loaded from
/Users/USERNAME/.gradle/caches/transforms-3/6c87f3acbf13b40ac5e88ec17ade8676/transformed/jetified-kotlin-
stdlib-1.5.31.jar!/kotlin/Unit.class
[        ] e:
/Users/USERNAME/.pub-cache/hosted/pub.dartlang.org/advertising_id-2.1.0/android/src/main/kotlin/com/os/op
erando/advertisingid/AdvertisingIdPlugin.kt: (51, 9): Class 'kotlin.Unit' was compiled with an
incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is
1.1.15.
[        ] The class is loaded from
/Users/USERNAME/.gradle/caches/transforms-3/6c87f3acbf13b40ac5e88ec17ade8676/transformed/jetified-kotlin-
stdlib-1.5.31.jar!/kotlin/Unit.class
[        ] e:
/Users/USERNAME/.pub-cache/hosted/pub.dartlang.org/advertising_id-2.1.0/android/src/main/kotlin/com/os/op
erando/advertisingid/AdvertisingIdPlugin.kt: (52, 35): Unresolved reference: thread
[        ] e:
/Users/USERNAME/.pub-cache/hosted/pub.dartlang.org/advertising_id-2.1.0/android/src/main/kotlin/com/os/op
erando/advertisingid/AdvertisingIdPlugin.kt: (55, 30): Class 'kotlin.Unit' was compiled with an
incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is
1.1.15.
[        ] The class is loaded from
/Users/USERNAME/.gradle/caches/transforms-3/6c87f3acbf13b40ac5e88ec17ade8676/transformed/jetified-kotlin-
stdlib-1.5.31.jar!/kotlin/Unit.class
[        ] e:
/Users/USERNAME/.pub-cache/hosted/pub.dartlang.org/advertising_id-2.1.0/android/src/main/kotlin/com/os/op
erando/advertisingid/AdvertisingIdPlugin.kt: (56, 32): Class 'kotlin.Unit' was compiled with an
incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is
1.1.15.
[        ] The class is loaded from
/Users/USERNAME/.gradle/caches/transforms-3/6c87f3acbf13b40ac5e88ec17ade8676/transformed/jetified-kotlin-
stdlib-1.5.31.jar!/kotlin/Unit.class
[        ] e:
/Users/USERNAME/.pub-cache/hosted/pub.dartlang.org/advertising_id-2.1.0/android/src/main/kotlin/com/os/op
erando/advertisingid/AdvertisingIdPlugin.kt: (59, 30): Class 'kotlin.Unit' was compiled with an
incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is
1.1.15.
[        ] The class is loaded from
/Users/USERNAME/.gradle/caches/transforms-3/6c87f3acbf13b40ac5e88ec17ade8676/transformed/jetified-kotlin-
stdlib-1.5.31.jar!/kotlin/Unit.class
[        ] e:
/Users/USERNAME/.pub-cache/hosted/pub.dartlang.org/advertising_id-2.1.0/android/src/main/kotlin/com/os/op
erando/advertisingid/AdvertisingIdPlugin.kt: (60, 32): Class 'kotlin.Unit' was compiled with an
incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is
1.1.15.
[        ] The class is loaded from
/Users/USERNAME/.gradle/caches/transforms-3/6c87f3acbf13b40ac5e88ec17ade8676/transformed/jetified-kotlin-
stdlib-1.5.31.jar!/kotlin/Unit.class
[        ] e:
/Users/USERNAME/.pub-cache/hosted/pub.dartlang.org/advertising_id-2.1.0/android/src/main/kotlin/com/os/op
erando/advertisingid/AdvertisingIdPlugin.kt: (60, 40): Unresolved reference: javaClass
[        ] e:
/Users/USERNAME/.pub-cache/hosted/pub.dartlang.org/advertising_id-2.1.0/android/src/main/kotlin/com/os/op
erando/advertisingid/AdvertisingIdPlugin.kt: (64, 43): Unresolved reference: thread
[        ] e:
/Users/USERNAME/.pub-cache/hosted/pub.dartlang.org/advertising_id-2.1.0/android/src/main/kotlin/com/os/op
erando/advertisingid/AdvertisingIdPlugin.kt: (67, 30): Class 'kotlin.Unit' was compiled with an
incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is
1.1.15.
[        ] The class is loaded from
/Users/USERNAME/.gradle/caches/transforms-3/6c87f3acbf13b40ac5e88ec17ade8676/transformed/jetified-kotlin-
stdlib-1.5.31.jar!/kotlin/Unit.class
[        ] e:
/Users/USERNAME/.pub-cache/hosted/pub.dartlang.org/advertising_id-2.1.0/android/src/main/kotlin/com/os/op
erando/advertisingid/AdvertisingIdPlugin.kt: (68, 32): Class 'kotlin.Unit' was compiled with an
incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is
1.1.15.
[        ] The class is loaded from
/Users/USERNAME/.gradle/caches/transforms-3/6c87f3acbf13b40ac5e88ec17ade8676/transformed/jetified-kotlin-
stdlib-1.5.31.jar!/kotlin/Unit.class
[        ] e:
/Users/USERNAME/.pub-cache/hosted/pub.dartlang.org/advertising_id-2.1.0/android/src/main/kotlin/com/os/op
erando/advertisingid/AdvertisingIdPlugin.kt: (71, 30): Class 'kotlin.Unit' was compiled with an
incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is
1.1.15.
[        ] The class is loaded from
/Users/USERNAME/.gradle/caches/transforms-3/6c87f3acbf13b40ac5e88ec17ade8676/transformed/jetified-kotlin-
stdlib-1.5.31.jar!/kotlin/Unit.class
[        ] e:
/Users/USERNAME/.pub-cache/hosted/pub.dartlang.org/advertising_id-2.1.0/android/src/main/kotlin/com/os/op
erando/advertisingid/AdvertisingIdPlugin.kt: (72, 32): Class 'kotlin.Unit' was compiled with an
incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is
1.1.15.
[        ] The class is loaded from
/Users/USERNAME/.gradle/caches/transforms-3/6c87f3acbf13b40ac5e88ec17ade8676/transformed/jetified-kotlin-
stdlib-1.5.31.jar!/kotlin/Unit.class
[        ] e:
/Users/USERNAME/.pub-cache/hosted/pub.dartlang.org/advertising_id-2.1.0/android/src/main/kotlin/com/os/op
erando/advertisingid/AdvertisingIdPlugin.kt: (72, 40): Unresolved reference: javaClass
[        ] e:
/Users/USERNAME/.pub-cache/hosted/pub.dartlang.org/advertising_id-2.1.0/android/src/main/kotlin/com/os/op
erando/advertisingid/AdvertisingIdPlugin.kt: (76, 28): Class 'kotlin.Unit' was compiled with an
incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is
1.1.15.
[   +2 ms] The class is loaded from
/Users/USERNAME/.gradle/caches/transforms-3/6c87f3acbf13b40ac5e88ec17ade8676/transformed/jetified-kotlin-
stdlib-1.5.31.jar!/kotlin/Unit.class
[        ] FAILURE: Build failed with an exception.
[        ] * What went wrong:
[        ] Execution failed for task ':advertising_id:compileReleaseKotlin'.
[        ] > Compilation error. See log for more details
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to
get more log output. Run with --scan to get full insights.
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 1m 0s
[        ] Deprecated Gradle features were used in this build, making it incompatible with Gradle
8.0.
[        ] Use '--warning-mode all' to show the individual deprecation warnings.
[        ] See
https://docs.gradle.org/7.0.2/userguide/command_line_interface.html#sec:command_line_warnings
[        ] 46 actionable tasks: 4 executed, 42 up-to-date
[ +405 ms] Running Gradle task 'bundleRelease'... (completed in 61,7s)
[   +3 ms] "flutter appbundle" took 63.350ms.
[   +3 ms] Gradle task bundleRelease failed with exit code 1
[        ] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      AndroidGradleBuilder.buildGradleApp
(package:flutter_tools/src/android/gradle.dart:383:9)
           <asynchronous suspension>
           #2      AndroidGradleBuilder.buildAab
(package:flutter_tools/src/android/gradle.dart:196:5)
           <asynchronous suspension>
           #3      BuildAppBundleCommand.runCommand
           (package:flutter_tools/src/commands/build_appbundle.dart:148:5)
           <asynchronous suspension>
           #4      FlutterCommand.run.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command.dart:1125:27)
           <asynchronous suspension>
           #5      AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      FlutterCommandRunner.runCommand
           (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
           <asynchronous suspension>
           #10     run.<anonymous closure>.<anonymous closure>
(package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #11     AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #12     main (package:flutter_tools/executable.dart:92:3)
           <asynchronous suspension>
           
           
[   +3 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[   +1 ms] exiting with code 1
```

**Comment by operando** [comment]
What is the kotlin version of your project?
I updated version 1.5.31 of kotlin in plugin 2.1.0.
You may need to update the kotlin version of your project to use plugin 2.1.0.

**Comment by appinteractive** [comment]
Thanks for the hint, could you add stuff like that to the change log?
